# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[docker_context]
disabled = true

[git_status]
conflicted = 'conflicted|'
up_to_date = 'up_to_date|'
untracked = 'untracked|'
stashed = 'stashed|'
modified = 'modified|'
staged = '[++\($count\)](green)|'
renamed = 'renamed|'
deleted = 'deleted|'
ahead = '⇡${count}|'
diverged = '⇕⇡${ahead_count}⇣${behind_count}|'
behind = '⇣${count}|'
