# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[docker_context]
disabled = true

[nodejs]
disabled = true

[php]
disabled = true
